### ISSUE TITLE
publish all proprietary levels from Joyride Labs under an open license

### ISSUE THREAD

**Issue by soenkehahn** [nikki-and-the-robots/nikki#1]
We have already agreed internally that we want to do that, it's just a matter of getting it done.

(CC: @qubodup)

**Comment by akien-mga** [comment]
Looking forward to it :)

**Comment by MCMic** [comment]
Any news on this?

**Comment by soenkehahn** [comment]
@akien-mga @MCMic @qubodup: I've created a PR for this: #15. I've added the story-mode data files under `data/story-mode`. If anyone can take a look, that'll be great, but I'm planning to close this ticket once I merge.

I've also changed the code so the game picks up the story mode from where it is now. I've only tested this on linux and I doubt it works on any other platform, though. We can create other tickets for fixing windows and mac builds (or linux builds, if there are problems).

**Comment by MCMic** [comment]
I can only test Linux also but I will test this when I find time.
Thank you for working on this!
I’ll make sure it gets packaged in AUR once released.

**Comment by MCMic** [comment]
Hum I cloned the sh/load branch and ran the game from src folder with ./linuxRunInPlace.sh but the game did not seem to contain the story mode. There was the buy menu item which points to http://buy.joyridelabs.de/
Am I doing it wrong?

**Comment by soenkehahn** [comment]
@MCMic: Thanks a lot for looking into this.

Not sure what exactly happens. But here's an idea: Can you manually remove the `.stack-work` directory and build again? I reworked the structure of the executables in `sh/load`, so I think you might still have a so-called `core` executable lying around when you built from `master` that has the old behavior. (I don't fully understand how you manage to start that via `linuxRunInPlace.sh`, but after deleting `.stack-work` I would hope you at least get a better error message.)

**Comment by soenkehahn** [comment]
I've merged #15 which adds the story mode. Closing this.

**Comment by MCMic** [comment]
@soenkehahn Thanks!
Could you tag this as a new release on github to ease packaging?

**Comment by soenkehahn** [comment]
@MCMic: Yes, happy to do that. Given that this is the first release in a long time and the first one with the story mode included, I'm thinking it should be version `2.0.0`. Do you have any opinion on this?

**Comment by MCMic** [comment]
No opinion at all :-)
For people who bought the game it may seem weird seeing a 2.0 out with nothing new. For people who only played the free version it makes sense. Maybe 1.1?

**Comment by soenkehahn** [comment]
Alright, tagged as `1.1.0`.

**Comment by MCMic** [comment]
@soenkehahn Any advice on how to package Nikki?
I’m trying to redo the PKGBUILD for ArchLinux so that it builds 1.1.0 from source but I’m not used to haskell and stack I’m lost.
The old PKGBUILD was using prebuilt nikki archives.

I did this: https://framabin.org/?ecefb75e6d9814bb#k2c080Bnds1iCoT+9nk91eqlWII+ZAVGgvZ8ASTWoSM=
It does build and install the nikki binary but it says "nikki: nikki: canonicalizePath: does not exist (Aucun fichier ou dossier de ce type)" when trying to start it.
I’m pretty sure I should copy the data folder somewhere but I’m not sure where, I can put it in /usr/share/nikki but how can I tell the binary where to look?
Running from the src folder with the runinplace script works fine.

The old PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nikki

**Comment by soenkehahn** [comment]
Yeah, the deployment mechanism is fairly custom, because we wanted to ship self-contained directories on linux. So `stack install` won't work, as it won't copy the assets. (The error message could be better though.)

What you could do instead is run `./linuxDeploy.hs`, after `stack setup ; stack build`. This will create a directory `./nikki` that should contain everything to run the game. This includes:

- A bash script `nikki.sh` to actually run it
- The actual binary (called `restarter` for historical reasons)
- All assets under `./data`
- An empty file called `yes_nikki_is_deployed`. This will cause the binary to pick up the assets from `./data`.
- A bunch of shared objects. These are being dynamically loaded by the binary. (For proper packaging `nikki` should probably try to use shared libraries that are packaged for Arch. But I think this should still work.)

As you can probably tell, there's a lot of technical legacy that is not ideal. As this was not primarily meant to be distributed via package managers.

Let me know if that helps. If not, could you open a new issue in this repo? About packaging on Arch? Just to keep discussions a bit easier to find...
