### ISSUE TITLE
ArchLinux packaging

### ISSUE THREAD

**Issue by MCMic** [nikki-and-the-robots/nikki#17]
So, I tried what you explained in https://github.com/nikki-and-the-robots/nikki/issues/1#issuecomment-380641917

First problem is it fills ~/.stack with 3.7G of files, which will stay there after people finish building the package. It would be better if it can use an internal folder instead of having left-overs in the home.

Also, it fails with: linuxDeploy.hs: not found: .stack-work/dist/x86_64-linux-nopie/Cabal-1.22.4.0/build/nikki/nikki
It seems the file which does exists is .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.22.4.0/build/nikki/nikki

Note the "-tinfo6-" difference

**Comment by soenkehahn** [comment]
Regarding the `-tinfo6-` bug: I've created this branch that hopefully fixes this: https://github.com/nikki-and-the-robots/nikki/tree/sh/dynamic-dist-dir. Could you test from that branch if that works for you, please?

Regarding `~/.stack`: Yeah, that's how `stack` works, it caches a lot of dependencies per user. I'm not that familiar with Arch's PKGBUILDs, is the idea that every user runs these builds, i.e. compiles their own binaries? Or can those be executed on build machines and then users just download the binaries?

I don't know of a way to let `stack` put these dependencies in a different location than `~/.stack`. You could try modifying `$HOME` before running `stack setup ; stack build`. Or we could ask e.g. on the stack mailing list.

Note that the old PKGBUILD that you linked to (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nikki) just downloaded the built binaries as tarballs from github and made the game available that way. I could also upload those binary tarballs for the newest release. Not sure how fast I could get to that though. And then you could amend the old PKGBUILD. I was assuming you wanted to create a package that builds `nikki` from source though. Do you want to build from source or would you be happy with just using precompiled binaries in your PKGBUILD?

**Comment by MCMic** [comment]
I will test the branch and get back to you.

Packages on AUR are built by each user when installing. Then if some of them have a lot of interest and a repo manager notice that he can host built version on its repo and it will be built once and for all. For games like nikki I expect it will stay in AUR with build-on-install.

I prefer to have a PKGBUILD that builds from source it’s the best way to make sure all the source is available and that the binary matches the available source.
That said stack is downloading/building tons of stuff I understand nothing about so I’d be lying if I said I can assure the binary I have contains only code I know about.
So, if it gets too complicated or eat up too much resource to build from source I may get back to prebuilt solution if such prebuilds are made available.
Officially I think we are supposed to name the package nikki-bin in this case and leave the possibility to have a built-from-source package named nikki.

**Comment by soenkehahn** [comment]
Thanks for the explanation. So, if we manage to talk `stack` into putting the cached dependencies into the build directory, will that directory then be removed after users build it? Otherwise they'd be equally stuck with 3.7G of unnecessary files on their machine.

And yes, I agree that building from source is the nicer option. Let me know when/if you give up and want me to upload binaries though. Or better yet, create an issue. :)

I've found this: https://groups.google.com/d/topic/haskell-stack/jnZjoSdId5U/discussion. This should help move the cache directory in a non-hacky way.

**Comment by MCMic** [comment]
With the patch from #18 I get: 

> copying .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.22.4.0/build/nikki/nikki
> copying ../data
> linuxDeploy.hs: "ldd-output:    linux-vdso.so.1 (0x00007ffd1cbab000)
>         libQtOpenGL.so.4 => /usr/lib/libQtOpenGL.so.4 (0x00007f0b58122000)
>         libQtGui.so.4 => /usr/lib/libQtGui.so.4 (0x00007f0b57447000)
>         libQtCore.so.4 => /usr/lib/libQtCore.so.4 (0x00007f0b56f5a000)
>         libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f0b56bd3000)
>         libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007f0b5695b000)
>         libopenal.so.1 => /usr/lib/libopenal.so.1 (0x00007f0b5668f000)
>         libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f0b56471000)
>         libm.so.6 => /usr/lib/libm.so.6 (0x00007f0b56125000)
>         librt.so.1 => /usr/lib/librt.so.1 (0x00007f0b55f1d000)
>         libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f0b55d19000)
>         libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f0b55a86000)
>         libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f0b5586f000)
>         libc.so.6 => /usr/lib/libc.so.6 (0x00007f0b554b8000)
>         libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f0b551ef000)
>         libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f0b54f64000)
>         libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f0b54d59000)
>         libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f0b54a1a000)
>         libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f0b54705000)
>         libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f0b544cf000)
>         libz.so.1 => /usr/lib/libz.so.1 (0x00007f0b542b8000)
>         libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f0b54063000)
>         libSM.so.6 => /usr/lib/libSM.so.6 (0x00007f0b53e5b000)
>         libICE.so.6 => /usr/lib/libICE.so.6 (0x00007f0b53c3f000)
>         libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f0b539fa000)
>         libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f0b537e8000)
>         /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f0b5841d000)
>         libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x00007f0b53570000)
>         libogg.so.0 => /usr/lib/libogg.so.0 (0x00007f0b53369000)
>         libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007f0b5313d000)
>         libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007f0b52e94000)
>         libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f0b52c84000)
>         libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f0b529d2000)
>         libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f0b527a1000)
>         libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f0b524eb000)
>         libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f0b522c2000)
>         libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f0b5204f000)
>         libffi.so.6 => /home/mcmic/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-7.10.2/lib/ghc-7.10.2/rts/libffi.so.6 (0x00007f0b51e42000)
>         libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f0b51c3b000)
>         libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f0b51a09000)
>         libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f0b517dd000)
>         libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f0b515d9000)
>         libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f0b513d3000)
> " (line 1, column 25):
> unexpected "("
> expecting space or "=>"
> CallStack (from HasCallStack):
>   error, called at /home/mcmic/dev/aur/nikki/src/nikki-1.1.0/src/linuxDeploy.hs:147:23 in main:Main
>

**Comment by soenkehahn** [comment]
I see. `./linuxDeploy.hs` calls `ldd` on the main binary to figure out what shared libraries it needs. And then it copies a few of them (the ones it deems non-standard on linux distros) into the `nikki` directory. For that it parses the output of `ldd` and on your system there is one less arrow (`=>`) than on mine. :(

We could fix the parser, but I think for this use-case (packaging for Arch) we don't even want the script to copy any shared objects, because the `nikki` package should just depend on the runtime versions of those libraries. So I could change the script to accept a command line flag to just disable copying of shared objects. Then it wouldn't matter that `ldd` output differs between systems. So it'd be something like `./linuxDeploy.hs --no-copy-shared-objects`. What do you think? (Any opinion on the exact flag?)

There's also other behavior of that deployment script that we probably don't need then anymore: it creates a wrapper script that is only needed to pick up those dynamic dependencies. Well, but one thing at a time, let's fix the `ldd` problem first.

**Comment by MCMic** [comment]
Yeah if it’s standard libraries it’s better not to copy anything. No opinion on the flag name.

**Comment by soenkehahn** [comment]
> Yeah if it’s standard libraries [...]

Well, it's not standard libraries in the sense that they are usually installed on vanilla systems by default. But I hope they are packaged by Arch and could be added as dependencies.

I've just pushed a commit to the same branch/pr: https://github.com/nikki-and-the-robots/nikki/pull/18. `./linuxDeploy.hs` now has a command line flag. Could you try that out, please?

**Comment by MCMic** [comment]
Seems to work well :-)
Do you confirm that I do not need to copy the file yes_nikki_is_deployed?

I’m using the same code as the old PKGBUILD now for installation, only the build step differs.

Could you list the dependencies I should add?
Right now I have:
makedepends=('cmake' 'pkg-config')
depends=('libsndfile' 'openal' 'qt4' 'libzip')

**Comment by soenkehahn** [comment]
> Do you confirm that I do not need to copy the file yes_nikki_is_deployed?

That seems right. I thought this was needed, but looking at the code now, I think it's not.

> Could you list the dependencies I should add?

I can't easily come up with an exhaustive list, sorry. Here's some dependencies that are definitely missing though:

makedepends: stack g++
depends: libzip libgmp

You can see all runtime dependencies by running `ldd` on the binary, e.g. by doing `ldd $(stack exec which nikki)`. Although, there's lots of false positives in there, I think. For example a lot of libraries there are just transitive dependencies of `Qt`.

The safest way is to start with a vanilla installation of arch (e.g. in a VM) and then try to build (or run) the package there and add dependencies when you get errors.

**Comment by MCMic** [comment]
Thanks!
So if you could merge the PR and tag a new minor it would be perfect.

**Comment by soenkehahn** [comment]
Done, tagged as `1.1.1`, codename `archie`.

**Comment by MCMic** [comment]
Perfect, this is now packaged.
I also made an annoucement here: https://linuxfr.org/users/mcmic/journaux/le-mode-histoire-de-nikki-and-the-robots-libere (in french)

Thank you very much for the time you spent on this, much appreciated!

**Comment by soenkehahn** [comment]
Awesome. :) My french is really bad, but I'll try to read it. And thanks to you for putting in the effort to package this.
